MCM\DemoBundle\Entity\PointCardUse:
    type: entity
    table: Use_PointCard
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cusId:
            type: integer
            column: cus_id
        pointCardId:
            type: integer
            column: PointCard_id
        amount:
            type: integer
            column: amount
        orderId:
            type: integer
            column: Order_id
        time:
            type: datetime
    lifecycleCallbacks: {  }
